version: 2.1
orbs:
  python: circleci/python@1.3.4
  aws-ecr: circleci/aws-ecr@6.15.0
jobs:
  test:
    executor:
      name: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          command: |
            pytest services/__tests__/sensors-test.py
          name: Running Test
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
workflows:
  build:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
      - aws-ecr/build-and-push-image:
          repo: iot-security
          tag: "latest,v0.1.${CIRCLE_BUILD_NUM}"
          path: .
          requires:
            - test
          filters:
            branches:
              only:
                - master
          context: AWS_DEPLOY
